name: lint

on:
  push:
    paths: "*.py"

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v7

      - name: Install Linter
        run: pip install ruff

  
    
